create table refund_order (
    id bigint generated by default as identity primary key,
    refund_no varchar(40) not null unique,
    payment_id bigint not null unique references payment_order(id),
    idempotency_key varchar(100) not null unique,
    amount decimal(19, 2) not null check (amount > 0),
    reason varchar(500) not null,
    status varchar(20) not null,
    order_status_before_refund varchar(30) not null,
    external_refund_no varchar(100) unique,
    failure_reason varchar(500),
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table refund_notification (
    id bigint generated by default as identity primary key,
    refund_id bigint not null references refund_order(id),
    notification_id varchar(100) not null unique,
    created_at timestamp with time zone not null
);

create index idx_refund_notification_refund_id on refund_notification(refund_id);
