create table product_image (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id) on delete cascade,
    object_key varchar(500) not null unique,
    original_filename varchar(255) not null,
    content_type varchar(100) not null,
    declared_size bigint not null check (declared_size > 0),
    actual_size bigint,
    etag varchar(200),
    status varchar(20) not null,
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_product_image_product_status on product_image(product_id, status);
