create table product (
    id bigint generated by default as identity primary key,
    name varchar(200) not null,
    description varchar(2000),
    status varchar(20) not null,
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table sku (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id),
    sku_code varchar(64) not null unique,
    name varchar(200) not null,
    price decimal(19, 2) not null check (price >= 0),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_sku_product_id on sku(product_id);
