create table inventory (
    id bigint generated by default as identity primary key,
    sku_id bigint not null unique references sku(id),
    available_quantity integer not null,
    reserved_quantity integer not null default 0,
    version bigint not null default 0,
    updated_at timestamp with time zone not null,
    check (available_quantity >= 0),
    check (reserved_quantity >= 0)
);
