create table customer_order (
    id bigint generated by default as identity primary key,
    order_no varchar(40) not null unique,
    status varchar(30) not null,
    total_amount decimal(19, 2) not null check (total_amount >= 0),
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table order_item (
    id bigint generated by default as identity primary key,
    order_id bigint not null references customer_order(id),
    sku_id bigint not null references sku(id),
    sku_code varchar(64) not null,
    sku_name varchar(200) not null,
    unit_price decimal(19, 2) not null check (unit_price >= 0),
    quantity integer not null check (quantity > 0),
    subtotal decimal(19, 2) not null check (subtotal >= 0),
    unique (order_id, sku_id)
);

create table inventory_reservation (
    id bigint generated by default as identity primary key,
    order_id bigint not null references customer_order(id),
    sku_id bigint not null references sku(id),
    quantity integer not null check (quantity > 0),
    status varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    unique (order_id, sku_id)
);

create index idx_order_item_order_id on order_item(order_id);
create index idx_inventory_reservation_order_id on inventory_reservation(order_id);
