create table payment_order (
    id bigint generated by default as identity primary key,
    payment_no varchar(40) not null unique,
    order_id bigint not null unique references customer_order(id),
    idempotency_key varchar(100) not null unique,
    amount decimal(19, 2) not null check (amount >= 0),
    status varchar(20) not null,
    external_transaction_no varchar(100) unique,
    failure_reason varchar(500),
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table payment_notification (
    id bigint generated by default as identity primary key,
    payment_id bigint not null references payment_order(id),
    notification_id varchar(100) not null unique,
    created_at timestamp with time zone not null
);

create index idx_payment_order_order_id on payment_order(order_id);
create index idx_payment_notification_payment_id on payment_notification(payment_id);
