create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    email varchar(254) not null unique,
    phone varchar(32) unique,
    status varchar(20) not null,
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_app_user_status on app_user(status);
