create table user_address (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    label varchar(50) not null,
    receiver_name varchar(100) not null,
    phone varchar(32) not null,
    province varchar(100) not null,
    city varchar(100) not null,
    district varchar(100) not null,
    detail_address varchar(500) not null,
    postal_code varchar(20),
    is_default boolean not null default false,
    version bigint not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_user_address_user_id on user_address(user_id);

alter table customer_order add column user_id bigint references app_user(id);
alter table customer_order add column receiver_name varchar(100);
alter table customer_order add column receiver_phone varchar(32);
alter table customer_order add column province varchar(100);
alter table customer_order add column city varchar(100);
alter table customer_order add column district varchar(100);
alter table customer_order add column detail_address varchar(500);
alter table customer_order add column postal_code varchar(20);

create index idx_customer_order_user_id_id on customer_order(user_id, id);
