alter table app_user add column password_hash varchar(100);
alter table app_user add column role varchar(20) not null default 'USER';

create table refresh_token (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    token_hash varchar(64) not null unique,
    family_id varchar(36) not null,
    expires_at timestamp with time zone not null,
    used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    replaced_by_token_id bigint references refresh_token(id),
    version bigint not null default 0,
    created_at timestamp with time zone not null
);

create index idx_refresh_token_family on refresh_token(family_id);
create index idx_refresh_token_user on refresh_token(user_id);
create index idx_refresh_token_expiry on refresh_token(expires_at);
