create table outbox_event (
    id bigint generated by default as identity primary key,
    event_id varchar(36) not null unique,
    aggregate_type varchar(50) not null,
    aggregate_id varchar(100) not null,
    event_type varchar(100) not null,
    payload text not null,
    status varchar(20) not null,
    attempts integer not null default 0,
    next_attempt_at timestamp with time zone not null,
    locked_until timestamp with time zone,
    last_error varchar(1000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    sent_at timestamp with time zone,
    version bigint not null default 0
);

create index idx_outbox_delivery
    on outbox_event(status, next_attempt_at);

create index idx_outbox_processing_lease
    on outbox_event(status, locked_until);

create index idx_outbox_aggregate
    on outbox_event(aggregate_type, aggregate_id);
